# .github/workflows/security-pipeline.yml (provided template)
name: Security-First CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    
    steps:
    - uses: actions/checkout@v4
    
    # INTENTIONALLY INCOMPLETE - participants must configure
    - name: Initialize CodeQL
      uses: # PARTICIPANTS MUST COMPLETE CONFIGURATION
      
    - name: SAST Analysis
      # PARTICIPANTS MUST IMPLEMENT SECURITY SCANNING
